In [1]:
import torch

In [2]:
print("PyTorch version:", torch._version_)

AttributeError: module 'torch' has no attribute '_version_'

In [3]:
print("PyTorch version:", torch.__version__
     )

PyTorch version: 2.7.1


In [4]:
x = torch.randn(3,4)

In [5]:
print("Tensor shape:", x.shape)

Tensor shape: torch.Size([3, 4])


In [6]:
print("Tensor data type:", x.dtype )

Tensor data type: torch.float32


In [12]:
print(x)

tensor([[ 0.0455,  0.4614, -0.4655,  0.5167],
        [ 0.6852,  1.8345,  1.3634,  0.2342],
        [ 1.0941,  0.8552, -2.0954, -1.0489]])


In [15]:
y = torch.randn(4,5)
z = torch.matmul(x,y)
c = x @ y
print("矩阵结果是:\n", z)
print("矩阵结果是:\n", c)

矩阵结果是:
 tensor([[-0.3745,  0.7203,  0.6504, -0.3762,  0.4499],
        [-0.4560,  2.2801, -0.3898,  4.1672, -2.2791],
        [-1.2157,  2.2147, -1.0622, -0.8421,  0.1407]])
矩阵结果是:
 tensor([[-0.3745,  0.7203,  0.6504, -0.3762,  0.4499],
        [-0.4560,  2.2801, -0.3898,  4.1672, -2.2791],
        [-1.2157,  2.2147, -1.0622, -0.8421,  0.1407]])
