In [2]:
import torch

In [7]:
print(torch.seed()) #随机生成64位随机数

15112921680102586294


In [15]:
print(torch.manual_seed(11))
# x = torch.manual_seed()
# print(x)

In [16]:
print(torch.initial_seed()) #返回原始种子值

11


In [18]:
print(torch.get_rng_state()) # 返回随机生成器状态

tensor([11,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)


In [23]:
rng_state1 = torch.get_rng_state()
print(rng_state1)
torch.set_rng_state(rng_state1 * 2)
rng_state2 = torch.get_rng_state()
print(rng_state2)

tensor([22,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
tensor([44,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
