In [1]:
import torch

In [2]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(x,w)
b = torch.add(w,1)
y = torch.mul(a,b)
y.backward()
print(w.grad)

tensor([5.])


In [3]:
w = torch.tensor([1.], requires_grad = True)
x = torch.tensor([2.], requires_grad = True)
a = torch.add(x,w)
b = torch.add(w,1)
y0 = torch.mul(a,b)
y1 = torch.add(a,b)
loss = torch.cat([y0, y1], dim=0)
grad_t = torch.tensor([1.,2.])
loss.backward(gradient = grad_t)
print(w.grad)

tensor([9.])


In [12]:
x = torch.tensor([3.0], requires_grad = True)
y = torch.pow(x,2)
grad1 = torch.autograd.grad(y, x,create_graph =True)
print(grad1)

(tensor([6.], grad_fn=<MulBackward0>),)


In [13]:
grad2 = torch.autograd.grad(grad1[0], x)
print(grad2)

(tensor([2.]),)
