In [6]:
import torch

In [ ]:
# 求所有元素积

In [2]:
a = torch.tensor([[1,2],[3,4]])
result = torch.prod(a)
print(result)

tensor(24)


In [3]:
result_dim = torch.prod(a, dim=0) #沿着0维（行）向量计算
print(result_dim)

tensor([3, 8])


In [5]:
result_keepdim = torch.prod(a, dim= 0, keepdim=True) #保持原始维度
print(result_keepdim)

tensor([[3, 8]])


In [7]:
# 求和

In [9]:
a = torch.rand(2,2)
print(a)

tensor([[0.4812, 0.9579],
        [0.6255, 0.8445]])
