In [1]:
import torch

In [7]:
w = torch.tensor([1.], requires_grad = True)
x = torch.tensor([2.], requires_grad = True)
for i in range(3):
    a = torch.add(x,w)
    b = torch.add(w,1)
    y = torch.mul(a,b)
    y.backward() # 自动执行反向传播并计算梯度（导数）存储到.grad中
    print(w.grad)
    # w.grad.zero_()

tensor([5.])
tensor([10.])
tensor([15.])


In [13]:
w = torch.tensor([1.], requires_grad = True)
x = torch.tensor([2.], requires_grad = True) 
a = torch.add(w,x)
b = torch.add(w,1)
y = torch.mul(a, b )
y.backward()
print(y.grad, w.grad, x.grad)
print(a.requires_grad, b.requires_grad, y.requires_grad)

None tensor([5.]) tensor([2.])
True True True


/var/folders/x7/y4w8ksb11hg0hskk24b0l09w0000gn/T/ipykernel_9586/396356581.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(y.grad, w.grad, x.grad)


In [17]:
w = torch.tensor([1.], requires_grad = True)
x = torch.tensor([2.], requires_grad = True)
a = torch.add(w,x)
b = torch.add(w,1)
y = torch.mul(a,b)
# w.add_(1)
a = torch.tensor([1])
print(id(a),a)
a = a + torch.tensor([1])
print(id(a),a)
a += torch.tensor([1])
print(id(a),a)

4784434096 tensor([1])
4783779456 tensor([2])
4783779456 tensor([3])
